### ISSUE TITLE
files do not show

### ISSUE THREAD

**Issue by neazoi** [Self-Evident/OneFileCMS#33]
when I try to see the list of files no files are shown. then, if I click once on the "folders first", the files are shown ok.

**Comment by Self-Evident** [comment]
(Almost two years later, but better late than never? :)
Thanks for the resolution cwal.  I've seen this issue as well, but only sporadically, so I was never able to do any real troubleshooting.  Your solution does work, but it I can't figure out why it's needed. (Because I'm not as smart as I think I am.)  Basically, Sort_and_Show() is one of the last things that happens when the index (file list) page loads, so I don't know why it fails to display the files sometimes.  Regardless, I'm gonna implement your solution in the next update (3.5.20), and close this at that time.

(Issues using CKEditor will be addressed seperately.)

**Comment by Self-Evident** [comment]
This issue was figured out & resolved. A different fix than menioned above: the initial call to Sort_and_Show() was moved to the end of the page, after every thing else is loaded, and it seems to have fixed it.
